version: '3.1'
services:
  stat-server:
    ports:
      - "9090:9090"

  statistic-db:
    image: postgres:14-alpine

  main-service:
    ports:
      - "8080:8080"

  explore-db:
    image: postgres:14-alpine
